name:                jarvis
version:             0.1.0.0
github:              "gillchristian/jarvis"
license:             MIT

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/gillchristian/jarvis#readme>

dependencies:
- base >= 4.7 && < 5
- calamity >=0.2.0 && <0.2.1
- data-default
- data-flags
- df1
- di
- di-core
- di-polysemy
- directory
- filepath
- generic-lens
- lens
- polysemy
- polysemy-plugin
- text
- text-show

library:
  source-dirs: src

default-extensions:
  - DataKinds
  - OverloadedLabels
  - OverloadedStrings
  - TypeApplications

ghc-options:
  - -fplugin=Polysemy.Plugin

executables:
  jarvis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jarvis

tests:
  jarvis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jarvis
